FROM rust:latest

RUN apt update && apt upgrade -y
RUN apt install -y \
    cmake \
    g++-mingw-w64-x86-64 \
    libvulkan-dev \
    libvulkan1 \
    mesa-vulkan-drivers

RUN rustup update
RUN rustup target add x86_64-pc-windows-gnu
RUN rustup toolchain install stable-x86_64-pc-windows-gnu

WORKDIR /app

CMD ["cargo", "build", "--target", "x86_64-pc-windows-gnu"]
